name: Pete LePage
markdown: kramdown
highlighter: pygments
paginate: 5
paginate_path: "blog/page:num"
permalink: /blog/:year/:month/:title/
destination: _build/
url: http://www.petelepage.com
feed_url: http://feeds.feedburner.com/petelepage
rss_path: static/
rss_post_limit: 50
sitemap:
    file: static/sitemap.xml
exclude: ["node_modules", "Gruntfile.js", "package.json"]
include: [".htaccess"]
sass:
    style: :compressed
gem: ["jekyll-tagging"]
tag_page_layout: tag
tag_page_dir: blog/tag
