name: Pete LePage
markdown: kramdown
pygments: true
paginate: 5
paginate_path: "blog/page:num"
permalink: /blog/:year/:month/:title.html
destination: _build/
url: https://www.petelepage.com
rss_path: static/
rss_post_limit: 50
sitemap:
    file: static/sitemap.xml
exclude: ["node_modules", "Gruntfile.js", "package.json"]
include: [".htaccess"]