application: petele-blog
version: 20140516-01
runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

default_expiration: "30d"

handlers:

- url: /assets
  static_dir: assets

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /
  static_files: index.html
  upload: index.html
  expiration: "60m"

- url: /index.html
  static_files: index.html
  upload: index.html
  expiration: "60m"

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "90d"

- url: /favicon.png
  static_files: static/favicon.png
  upload: static/favicon.png
  expiration: "90d"

- url: /humans.html
  static_files: static/humans.html
  upload: static/humans.html
  expiration: "90d"

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: "90d"

- url: /rss.xml
  static_files: static/rss.xml
  upload: static/rss.xml
  expiration: "1h"

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml
  expiration: "1h"

- url: /blog
  script: app.application

- url: /blog/.*
  script: app.application

- url: /photography
  script: app.application

- url: /photography/.*
  script: app.application

- url: /presentations
  script: app.application

- url: /presentations/.*
  script: app.application

- url: /scratch
  script: app.application

- url: /scratch/.*
  script: app.application

- url: /flush/.*
  script: app.application
  login: admin

- url: .*
  static_files: static/404.html
  upload: static/404.html
  expiration: "10m"
  application_readable: true