application: petele-blog
version: 20140516-01
runtime: python27
threadsafe: true
api_version: 1

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest


handlers:
- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /favicon.png
  static_files: static/favicon.png
  upload: static/favicon.png

- url: /humans.html
  static_files: static/humans.html
  upload: static/humans.html

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /rss.xml
  static_files: static/rss.xml
  upload: static/rss.xml

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

- url: .*
  script: app.application